---
version: 2
workflows:
  version: 2
  test:
    jobs:
      - format_check
      - validation_check

jobs:
  format_check:
    docker:
      - image: "hashicorp/terraform:0.12.13"
    steps:
      - checkout
      - run:
          name: Check terraform formatting
          command: terraform fmt -check=true -write=false -diff
  validation_check:
    working_directory: ~
    docker:
      - image: "hashicorp/terraform:0.12.13"
    steps:
      - checkout
      - run:
          name: create fake license file
          command: touch ~/fake.rli
      - run:
          name: create fake tfvars file and provider stub
          command: echo -e "domain = \"example.com\"\nlicense_file = \"~/fake.rli\"\nvpc_id = \"vpc-1234567890\"\n" > terraform.tfvars
      - run:
          name: create provider stub
          command: echo -e "provider \"aws\" {\n  region = \"us-west-2\"\n}\n" > provider.tf
      - run:
          name: init configs and check if valid
          command: terraform init && terraform validate
