# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://www.hashicorp.com/security.html
    about: Please report security vulnerabilities responsibly.
