#cloud-config

ssh_import_id:
${import_key != "" ? "- ${import_key}" : ""}

write_files:
- path: /etc/ptfe/role
  owner: root:root
  permissions: "0444"
  content: "${role}"

- path: /etc/ptfe/ptfe_url
  owner: root:root
  permissions: "0644"
  content: "${installer_url}"

- path: /etc/ptfe/bootstrap-token
  owner: root:root
  permissions: "0500"
  content: ${bootstrap_token}

- path: /etc/ptfe/cluster-api-endpoint
  owner: root:root
  permissions: "0500"
  content: ${cluster_api_endpoint}

- path: /etc/ptfe/health-url
  owner: root:root
  permissions: "0400"
  content: "${health_url}"

%{ if airgap_installer_url != "" }
- path: /etc/ptfe/airgap-installer-url
  owner: root:root
  permissions: "0644"
  content: ${airgap_installer_url}
%{ endif }

- path: /var/lib/cloud/scripts/per-once/install-ptfe.sh
  owner: root:root
  permissions: "0555"
  encoding: b64
  content: ${install_ptfe_sh}

- path: /etc/ptfe/proxy-url
  owner: root:root
  permissions: "0400"
  content: "${proxy_url}"

- path: /etc/ptfe/custom-ca-cert-url
  owner: root:root
  permissions: "0400"
  content: "${ca_bundle_url}"

- path: /etc/apt/apt.conf.d/00aaa_proxy
  owner: root:root
  permissions: "0400"
  content: |
    Acquire::http::proxy "${proxy_url}";
    Acquire::https::proxy "${proxy_url}";

packages:
- jq
- chrony
- ipvsadm
- unzip
- wget
